### ISSUE TITLE
No .apple tld domains

### ISSUE THREAD

**Issue by tristanratz** [lavgup/apple-domains#2]
Apple does own the https://apple tld

**Comment by lavgup** [comment]
I am aware of this. However, this site will only list domains that resolve (e.g. they own `apple.car` but it doesn't resolve) and I am yet to find any domains with the `.apple` TLD that resolve. 

If you know of any, I could most definitely add them to the site.

**Comment by tristanratz** [comment]
Here are some of the registered domains:
- experience.apple
- applecard.apple
- signtime.apple
- newsroom.apple
- ...

Other domains are listed here:
https://dnslytics.com/tld/apple

Interesting project btw

Thanks

**Comment by lavgup** [comment]
Ah, thanks for that. I will add them to the site shortly.
